on:
  pull_request:
  push:
    branches:
      - main

# https://github.community/t/concurrency-cancel-in-progress-but-not-when-ref-is-master/194707/4
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
    - run: sbt -v
           scalafmtCheckAll
           scalafmtSbtCheck
           test
           scripted
           warningsAll
    - if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
      uses: actions/upload-artifact@v3
      with:
        name: warnings.json
        path: target/warnings/warnings.json
    - id: download_previous_warnings
      if: (github.event_name == 'pull_request') && (github.base_ref == 'main')
      uses: dawidd6/action-download-artifact@v2
      with:
        if_no_artifact_found: 'warn'
        branch: ${{ github.base_ref }}
        path: target/warnings/tmp
    - if: (github.event_name == 'pull_request') && (github.base_ref == 'main') && (steps.download_previous_warnings.outputs.found_artifact == 'true')
      run: mv target/warnings/tmp/warnings.json/warnings.json target/warnings/warnings-previous.json
    - if: (github.event_name == 'pull_request') && (github.base_ref == 'main') && (steps.download_previous_warnings.outputs.found_artifact == 'true')
      run: sbt warningsDiff
    - if: (github.event_name == 'pull_request') && (github.base_ref == 'main') && (steps.download_previous_warnings.outputs.found_artifact == 'true')
      run: |
        if [ -s "target/warnings/warnings.diff" ]; then
          echo "# warnings diff" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```diff" >> $GITHUB_STEP_SUMMARY
          cat target/warnings/warnings.diff >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        else
          echo "# no warnings diff" >> $GITHUB_STEP_SUMMARY
        fi
